### ISSUE TITLE
ValueError while using part segmentation

### ISSUE THREAD

**Issue by thirdlastletter** [charlesq34/pointnet2#125]
Hi,

I`m trying to use train.py with the example data for the part segmentation. I get the following output though:

`('Airplane', [0, 1, 2, 3])
('Bag', [4, 5])
('Cap', [6, 7])
('Car', [8, 9, 10, 11])
('Chair', [12, 13, 14, 15])
('Earphone', [16, 17, 18])
('Guitar', [19, 20, 21])
('Knife', [22, 23])
('Lamp', [24, 25, 26, 27])
('Laptop', [28, 29])
('Motorbike', [30, 31, 32, 33, 34, 35])
('Mug', [36, 37])
('Pistol', [38, 39, 40])
('Rocket', [41, 42, 43])
('Skateboard', [44, 45, 46])
('Table', [47, 48, 49])
('Airplane', [0, 1, 2, 3])
('Bag', [4, 5])
('Cap', [6, 7])
('Car', [8, 9, 10, 11])
('Chair', [12, 13, 14, 15])
('Earphone', [16, 17, 18])
('Guitar', [19, 20, 21])
('Knife', [22, 23])
('Lamp', [24, 25, 26, 27])
('Laptop', [28, 29])
('Motorbike', [30, 31, 32, 33, 34, 35])
('Mug', [36, 37])
('Pistol', [38, 39, 40])
('Rocket', [41, 42, 43])
('Skateboard', [44, 45, 46])
('Table', [47, 48, 49])
pid: 20236
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    train()
  File "train.py", line 102, in train
    pointclouds_pl, labels_pl = MODEL.placeholder_inputs(BATCH_SIZE, NUM_POINT)
ValueError: too many values to unpack`

Does anyone know how to solve this? What is meant with `too many values to unpack`? I am using the ShapeNet model.
Thank you!

**Comment by tansinjahan** [comment]
I am also getting the similar error. Does anyone have any suggestion?

('Airplane', [0, 1, 2, 3])
('Bag', [4, 5])
('Cap', [6, 7])
('Car', [8, 9, 10, 11])
('Chair', [12, 13, 14, 15])
('Earphone', [16, 17, 18])
('Guitar', [19, 20, 21])
('Knife', [22, 23])
('Lamp', [24, 25, 26, 27])
('Laptop', [28, 29])
('Motorbike', [30, 31, 32, 33, 34, 35])
('Mug', [36, 37])
('Pistol', [38, 39, 40])
('Rocket', [41, 42, 43])
('Skateboard', [44, 45, 46])
('Table', [47, 48, 49])
('Airplane', [0, 1, 2, 3])
('Bag', [4, 5])
('Cap', [6, 7])
('Car', [8, 9, 10, 11])
('Chair', [12, 13, 14, 15])
('Earphone', [16, 17, 18])
('Guitar', [19, 20, 21])
('Knife', [22, 23])
('Lamp', [24, 25, 26, 27])
('Laptop', [28, 29])
('Motorbike', [30, 31, 32, 33, 34, 35])
('Mug', [36, 37])
('Pistol', [38, 39, 40])
('Rocket', [41, 42, 43])
('Skateboard', [44, 45, 46])
('Table', [47, 48, 49])
pid: 28519
Traceback (most recent call last):
  File "train.py", line 322, in <module>
    train()
  File "train.py", line 97, in train
    pointclouds_pl, labels_pl = MODEL.placeholder_inputs(BATCH_SIZE, NUM_POINT)
ValueError: too many values to unpack

**Comment by tansinjahan** [comment]
It seems that the default model name in part_seg/train.py should be 'pointnet2_part_seg' which I had mistakenly set to 'pointnet2_sem_seg'. Never mind it is working fine now.

**Comment by thirdlastletter** [comment]
Yes I also made the same mistake!
