### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by erlikn** [charlesq34/pointnet2#141]
Hi, I am getting a segmentation fault while I am trying to run the train.py in Ubuntu 18.04, with Python3 using Tensorflow 1.14, with CUDA 10.0 and CuDnn 7.6.

Tracing the pipeline, I figured segmentation fault is happening at the farthest point sampling that utilizes tf_sampling_so.so

I am using g++ 7.4 to compile the .so files. I am not getting any errors, except few warnings during their compile.

Would you be able to suggest a solution? 
Thanks

**Comment by vhanded** [comment]
I am facing the same problem, TF 1.14, CUDA 10.1, CUDNN 7.6

**Comment by erlikn** [comment]
Ok, I got a solution.
The issue is with the version of the g++ (7.4.0) on Ubuntu 18.04. 
Simply installing the g++-4.8 and using it to build the tf_ops solved the issue.
