### ISSUE TITLE
Is T-net missing inside the pointnet2?

### ISSUE THREAD

**Issue by aGIToz** [charlesq34/pointnet2#179]
Hello,
Thank you for sharing your code.

In the original pointnet there was T-net (transfrom_nets) to bring invariance to the geometric transformation. Since pointnet2 basically implements the pointnet recursively I was thinking that transfrom_nets has to implemented recursively too. But I couldn't find the use of transfom_nets in point-net2.
I suppose t-net are not used in pointnet2? 

Kindly  confirm

**Comment by dariush-salami** [comment]
I think in PointNet++, they have made the model geometric transformation invariant through data augmentation. I believe there is no specific part responsible for this in PointNet++.

**Comment by aGIToz** [comment]
Yes you are right, I figured that out going through the paper of pointnet++.

**Comment by kuzand** [comment]
Where in the paper does it say about this? I am still not sure how PointNet++ achieves invariance under geometric transformations.

**Comment by dariush-salami** [comment]
AS I mentioned before, they don't have any specific mechanism for geometric transformation invariant. They augment the training data on-the-fly to somehow contribute to the geometric transformation invariant. In PointNet they had transformer network module, but in PointNet++ they have removed it.

**Comment by kuzand** [comment]
> AS I mentioned before, they don't have any specific mechanism for geometric transformation invariant. They augment the training data on-the-fly to somehow contribute to the geometric transformation invariant. In PointNet they had transformer network module, but in PointNet++ they have removed it.

So what was the reason for not including the T-Nets in PointNet++? It's a little bit strange that they doesn't mention it in the paper, since the T-Nets are crucial for the PointNet. I believe that they have tried the T-Nets on PointNet++ but they didn't work well (didn't lead to invariance under geometric transformations as in the PointNet). It would be nice though to understand the reason why.

**Comment by toannguyen1904** [comment]
the same question from me
