### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by lfs119** [charlesq34/pointnet2#19]
Hi,when i try to run classification code,there is a problem:"tf_ops/grouping/tf_grouping_so.so: undefined symbol: _ZN10tensorflow16KernelDefBuilderD2Ev".
my environment works on PointNet , gcc=5.40  tensorflow=1.2.0. I have tried to delete "-O2 -D_GLIBCXX_USE_CXX11_ABI=0", however, it does not work. do you have some advance?

**Comment by julians89** [comment]
Make sure to double check, which libs u are linking against, while building the tf ops. This is most probably a dynamic linking issue. Try to add something like -ltensorflow_framework.

**Comment by charlesq34** [comment]
HI @lfs119 

you need to make sure the library address you have is the same at that in the compile script :)

**Comment by hanafusman** [comment]
What about if I used a virtual environment to install tensorflow?

**Comment by lfs119** [comment]
Thanks a lot! I had solved that problem by updating TF's version.

**Comment by hanafusman** [comment]
@lfs119 which version of tensor flow? Also did you run it on a GPU?

**Comment by lfs119** [comment]
tensorflow-gpu==1.3.0

**Comment by vistart** [comment]
@lfs119 please close issue if solved.

**Comment by Mmmoran** [comment]
> HI @lfs119
> 
> you need to make sure the library address you have is the same at that in the compile script :)

> HI @lfs119
> 
> you need to make sure the library address you have is the same at that in the compile script :)

@charlesq34  My environment was tf 1.10 and cuda 9.0 g++version 5.8. my lib and include paths were true and then i was also troubled with this error! Was the question maybe my environment？
