### ISSUE TITLE
KeyError: 'FarthestPointSample' - When trying restore the pre-trained model 

### ISSUE THREAD

**Issue by vajrag** [charlesq34/pointnet2#204]
Hello,

When I am trying to restore/load the pre-trained model, I get a **_KeyError: 'FarthestPointSample_**'. I am not really sure why this is happening.

I am using the code below to restore the model. I have used `pointnet2_cls_msg` and `pointnet2_cls_ssg` models which gives the same error. 
`saver = tf.train.import_meta_graph("msg_model.ckpt.meta")
sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True))
saver.restore(sess, tf.train.latest_checkpoint("./"))`

System specifications are: 
tf-gpu = 1.14.0(both for training and restoring)
cuda = 11.0
python= 3.6

I appreciate any hints/solutions to resolve this issue.
Thank you

**Comment by irisliucy** [comment]
@vajrag Have you solved the issue? I have the same issue and would appreciate some pointers. 

Thank you
