### ISSUE TITLE
Undefined name 'tnet' in utils/pointnet_util.py

### ISSUE THREAD

**Issue by cclauss** [charlesq34/pointnet2#21]
https://github.com/charlesq34/pointnet2/blob/master/utils/pointnet_util.py#L49

flake8 testing of https://github.com/charlesq34/pointnet2 on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./utils/pointnet_util.py:49:23: F821 undefined name 'tnet'
        grouped_xyz = tnet(grouped_xyz, tnet_spec)
                      ^
1     F821 undefined name 'tnet'
```

[flake8](https://pypi.python.org/pypi/flake8) is saying is that if __sample_and_group()__ is called with a __tnet_spec__ parameter that is not None then [NameError](https://docs.python.org/3/library/exceptions.html#NameError) might be raised at runtime which would halt the script.

**Comment by charlesq34** [comment]
Hi @cclauss 

Thanks for pointing that, I have removed that argument.
