### ISSUE TITLE
Is there a way to apply pointNet++ on Mac?

### ISSUE THREAD

**Issue by Stanfording** [charlesq34/pointnet2#211]
Using the TensorFlow from Apple https://github.com/apple/tensorflow_macos in Miniforge environment and pointNet++ code from Keras' guide https://keras.io/examples/vision/pointnet/ will result a segmentation fault. I don't know if it is because of the m1 chip, or because of the code. It would be great if pointNet++ works on Mac, which will enhance a greater AI community including Mac users....

**Comment by monjoybme** [comment]
@Stanfording As long as you've installed all the required packages, there is no issue with Mac.

**Comment by Stanfording** [comment]
> @Stanfording As long as you've installed all the required packages, there is no issue with Mac.

There is a segmentation fault issue which I believe is not due to uninstall packages. To solve this issue, I have to turn off some layers, which means it is pointNet++ no more.....

**Comment by Stanfording** [comment]
> @Stanfording As long as you've installed all the required packages, there is no issue with Mac.

Or perhaps, it is because I am using M1 Mac? It would be so great if PointNet can run on M1 chip!

**Comment by Stanfording** [comment]
With tensorflow 2.5.0, PointNet++ can now run on m1 chip MacOS
