### ISSUE TITLE
Which model is for Scannet？

### ISSUE THREAD

**Issue by cissy123** [charlesq34/pointnet2#46]
I have tried all the models of segmentation, but it seems that there is no avaliable model for running Scannet. Please help me. Thanks.

**Comment by kxhit** [comment]
I meet the same issue. It seems like a stupid question and you solved it.  Please help me!

**Comment by kxhit** [comment]
@cissy123  any suggestions? Please!!

**Comment by OmarAhmadien** [comment]
@kxhit That might help: [#issue78](https://github.com/charlesq34/pointnet2/issues/78)
