### ISSUE TITLE
problem with tf_interpolate

### ISSUE THREAD

**Issue by mf27** [charlesq34/pointnet2#5]
I have tensorflow v1.3 and nvcc v7.5.17.
I tested
`python pointnet2_cls_msg.py`
and get the following error:
`tensorflow.python.framework.errors_impl.NotFoundError: ../tf_ops/3d_interpolation/tf_interpolate_so.so: undefined symbol: _ZN10tensorflow11TensorShapeC1ENS_3gtl10ArraySliceIxEE`

**Comment by xcyan** [comment]
You can probably recompile the TF cpp binding on your side:
https://www.tensorflow.org/extend/adding_an_op

**Comment by mf27** [comment]
Ok, I compiled tensorflow without the option
`--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"`
(although it's nicely pointed to in installation notes). After recompiling it works fine.
