### ISSUE TITLE
Per point segmentation output

### ISSUE THREAD

**Issue by pavan4** [charlesq34/pointnet2#60]
As I understand from the paper, segmentation network is supposed to output a per pixel prediction of the class. But the model `pointnet2_sem_seg`  seems to be `BxNx3, output Bxnum_class` which basically means it is a classification output and there is no per pixel predicted output? 

https://github.com/charlesq34/pointnet2/blob/24ebc8a82b62045c187eb1f2c74451bf7ddb03c6/models/pointnet2_sem_seg.py#L19

Please let me know if I am wrong?

**Comment by Bierfass** [comment]
I'm also searching for this. Did you find something?
