### ISSUE TITLE
Can't download the dataset

### ISSUE THREAD

**Issue by Guoxs** [charlesq34/pointnet2#63]
nice work!
I tried to download the dataset "modelnet40_normal_resampled.zip" and "shapenetcore_partanno_segmentation_benchmark_v0_normal.zip" using VPN but failed. I can access to Google and Stanford web page, I don't know why this problem happened. 
would you please check the dataset download settings? if you can offer a google drive version or dropbox version, that would be great nice!
by the way, I'm in China.

**Comment by ThibaultGROUEIX** [comment]
Same issue here,
Best 
Thibault

**Comment by kxhit** [comment]
Same problem!!!

**Comment by yangchzh5** [comment]
Thanks! It can download now~

**Comment by donnyruixu** [comment]
Hi,
I still cannot download the data set.
Insecure connection and expired certification occur when the link is opened with firefox.
