### ISSUE TITLE
Cannot load my own data

### ISSUE THREAD

**Issue by OmarAhmadien** [charlesq34/pointnet2#74]
I downloaded the per-processed scannet dataset, which contains two pickle files:
scannet_train.pickle and scannet_test.pickle

I cannot understand the last two lines I show here from scannet_dataset.py 
How is it possible to load the labels and the points from the same file!
while scannet_train.pickle contains only xyz points.

My data is xyz and labels and I cannot load them to work with pointnet2.

class ScannetDatasetVirtualScan():
    def __init__(self, root, npoints=8192, split='train'):
        self.npoints = npoints
        self.root = root
        self.split = split
        self.data_filename = os.path.join(self.root, 'scannet_%s.pickle'%(split))
        with open(self.data_filename,'rb') as fp:
            **self.scene_points_list = pickle.load(fp)**
           **self.semantic_labels_list = pickle.load(fp)**

**Comment by Bierfass** [comment]
I also stumbled across this but i found if you save it like this it is possible to load two things from one file.
with open(out_filename + '_train.pickle', 'wb') as handle:
        pickle.dump(data[0:split], handle, protocol=pickle.HIGHEST_PROTOCOL)
        pickle.dump(label[0:split], handle, protocol=pickle.HIGHEST_PROTOCOL)
with open(out_filename + '_test.pickle', 'wb') as handle:
        pickle.dump(data[split:], handle, protocol=pickle.HIGHEST_PROTOCOL)
        pickle.dump(label[split:], handle, protocol=pickle.HIGHEST_PROTOCOL)
hope it helps :)

**Comment by OmarAhmadien** [comment]
Thanks @Bierfass . Yes you are right loading twice brings the second object that has been dumped later.
