### ISSUE TITLE
undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by ZergL1014** [charlesq34/pointnet2#82]
I've seen issue #48 but still got this problem
I'm using Tensorflow1.8 on CentOS Linux 7.3 with cuda9.0 cudnn7.0 and python3.5
Here's my script:

nvcc=/usr/local/cuda-8.0/bin/nvcc
cudalib=/usr/local/cuda-8.0/lib64/
tensorflow=/public/home/scsc/zjc/env3/lib/python3.5/site-packages/tensorflow/include
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')

$nvcc -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -c -o tf_sampling_g.cu.o tf_sampling_g.cu -I -I$TF_INC -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -O2

g++ -std=c++11 tf_sampling.cpp tf_sampling_g.cu.o -o tf_sampling_so.so -shared -fPIC -I $tensorflow -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework -lcudart -L $cudalib -02

**Comment by Bierfass** [comment]
Have you tried it without the -D_GLIBCXX_USE_CXX11_ABI=0 for the nvcc compiler?

**Comment by ZergL1014** [comment]
Thanks for your reply!
I've tried it and it didn't work.
In adition we have both cuda8.0 and cuda9.0 in public server.

**Comment by ZergL1014** [comment]
Using tf1.3 and finally worked

**Comment by Bierfass** [comment]
Have you been using a precompiled version of Tensorflow 1.8?

**Comment by ZergL1014** [comment]
@Bierfass What is precompiled version?
I ran my project on TF1.8.0rc0 and TF1.7.0 earlier today.
It turned out 'Failed to load the native TensorFlow runtime' on TF1.8.0rc0
and 'undefined symblo' on TF1.7.0
Thank you for your patience :)

**Comment by Bierfass** [comment]
So you compiled them yourself? 
With precompiled I meant the pip version of tensorflow

**Comment by ZergL1014** [comment]
@Bierfass I always install tensorflow by pip.
