### ISSUE TITLE
the testing code for Scannet?

### ISSUE THREAD

**Issue by kkyan1995** [charlesq34/pointnet2#91]
do you have the testing code for Scannet ? i have done the train for it ? at that time , i'd like the testing code.
thank you a lot .
@charlesq34

**Comment by OmarAhmadien** [comment]
@kkyan1995 Please look at this: [Github: pointnet2_semantic](https://github.com/mathieuorhan/pointnet2_semantic). Especially predict.py.

**Comment by kkyan1995** [comment]
@OmarAhmadien ,thank you very much for your answer.

**Comment by OmarAhmadien** [comment]
@kkyan1995 You are welcome. Please close this issue if your problem is solved.
Thanks!

**Comment by longmalongma** [comment]
> @OmarAhmadien ,thank you very much for your answer.

have you ｃompleted test on the scannet?

**Comment by longmalongma** [comment]
> @kkyan1995 You are welcome. Please close this issue if your problem is solved.
> Thanks!

have you ｃompleted test on the scannet?can your codes generate visualization of segmentation results?

**Comment by medif** [comment]
@OmarAhmadin can you please provide me the testing code pf scannet., i had some issue with predict.py

**Comment by houhaol** [comment]
@longmalongma @medif @kkyan1995 @OmarAhmadin Anyone test the scannet successfully? I also had some issue using predict.py for scannet.
