### ISSUE TITLE
how to train other data by scannet?

### ISSUE THREAD

**Issue by kkyan1995** [charlesq34/pointnet2#93]
i want to train my data by scannet code , should i need to modify the code as followong ?
the code in scannet.py:
    def __getitem__(self, index):
        point_set = self.scene_points_list[index]
        semantic_seg = self.semantic_labels_list[index].astype(np.int32)
        coordmax = np.max(point_set,axis=0)
	coordmin = np.min(point_set,axis=0)
	smpmin = np.maximum(coordmax-[1.5,1.5,3.0], coordmin)
	smpmin[2] = coordmin[2]
	smpsz = np.minimum(coordmax-smpmin,[1.5,1.5,3.0])
	smpsz[2] = coordmax[2]-coordmin[2]
	isvalid = False
	for i in range(10):
	    curcenter = point_set[np.random.choice(len(semantic_seg),1)[0],:]
	    curmin = curcenter-[0.75,0.75,1.5]
	    curmax = curcenter+[0.75,0.75,1.5]
	    curmin[2] = coordmin[2]
	    curmax[2] = coordmax[2]
	    curchoice = np.sum((point_set>=(curmin-0.2))*(point_set<=(curmax+0.2)),axis=1)==3
	    cur_point_set = point_set[curchoice,:]
	    cur_semantic_seg = semantic_seg[curchoice]
	    if len(cur_semantic_seg)==0:
		continue
	    mask = np.sum((cur_point_set>=(curmin-0.01))*(cur_point_set<=(curmax+0.01)),axis=1)==3
	    vidx = np.ceil((cur_point_set[mask,:]-curmin)/(curmax-curmin)*[31.0,31.0,62.0])
	    vidx = np.unique(vidx[:,0]*31.0*62.0+vidx[:,1]*62.0+vidx[:,2])
	    isvalid = np.sum(cur_semantic_seg>0)/len(cur_semantic_seg)>=0.7 and len(vidx)/31.0/31.0/62.0>=0.02
	    if isvalid:
		break

can i modify the [1.5,1.5,3.0] and [0.75,0.75,1.5] or other code as the range of my data is different with scannet code ?
if i can , which i need modify as well ?
thanks a lot .

**Comment by kkyan1995** [comment]
what the meaning of [1.5,1.5,3.0] , which of them represent ?

**Comment by Bierfass** [comment]
That are the voxel dimensions. You can modify them as you need but you schould change the radius in the sem seg model accordingly

**Comment by kkyan1995** [comment]
@Bierfass ,thank you a lot , can I ask you a question as well , then what  the representation of [31.0,31.0,62.0] , and if I replace [1.5,1.5,3.0] with 【4.0,4.0,3.0】，which should i change with the radius ?

**Comment by Bierfass** [comment]
I don't really know what this [31.0,31.0,62.0] is. But you don't need to change it anyway. 
You need to change the half voxel size  [0.75,0.75,1.5] as well. 
For me to multiply the radius with the length of X worked well but it can be less.

**Comment by kkyan1995** [comment]
@Bierfass  ,yes ,I have modified [0.75,0.75,1.5] to [2.0,2.0,3.0] , but there is still a puzzle for the modification of radius , should I modify four of the radius to 0.3 , 0.6, 1.2, 2.0 or modify them to 0.1*X( x is 4.0/1.5 ?) , 0.2*X , 0.4*X , 0.8*X ?

**Comment by Bierfass** [comment]
I suggest you try it out. 0.1X x is 4.0/1.5 sounds good.
I used a 36, 36 as voxel size so i had to modify the radius because of the low point density in my pointcloud (6.7 points/m^2).

**Comment by OmarAhmadien** [comment]
@kkyan1995  @Bierfass  
Hello guys,
I came across this fork: [Pointnet2_semantic](https://github.com/mathieuorhan/pointnet2_semantic). It is a fine piece of work! Very neat and well presented. I think it might help you!

**Comment by kkyan1995** [comment]
@Bierfass, ok , well  thank you a lot for answering my question!

**Comment by brbzjl** [comment]
what's kind of effect is that 10 loops here?
